module URI
  class HTTP
  end
end

module Net
  class HTTP
  end

  class HTTPResponse
  end
end

module Benfalk
  class Fetcher
    attr_reader urls: Array[String]
    attr_reader retry_limit: Integer

    class RetryLimitExceeded < Exception
    end

    SERVER_ERROR_CODES: Range[Integer]

    # retry_limit: 5
    def initialize: (Array[String] urls, ?retry_limit: Integer) -> void

    def call: () -> Array[Net::HTTPResponse]

    private

    def fetch: (URI::HTTP uri) -> Net::HTTPResponse

    def uris: () -> Array[URI::HTTP]
  end
end
